stages:
  - build
  - test

variables:
  PHP_VERSION: "8.3"
  COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.composer/cache"

cache:
  paths:
    - .composer/cache
    - vendor/

build:
  stage: build
  image: php:${PHP_VERSION}-cli
  before_script:
    - apt-get update && apt-get install -y unzip git
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  script:
    - composer install --prefer-dist --no-progress --no-suggest --no-interaction
  artifacts:
    paths:
      - vendor/

test:
  stage: test
  image: php:${PHP_VERSION}-cli
  script:
    - ./vendor/bin/phpunit --configuration phpunit.xml