name: Static Analysis

on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: 8.3

      - uses: php-actions/phpstan@v3
        with:
          php_version: 8.3
          configuration: phpstan.neon
          memory_limit: 512m
