name: Tests

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: 8.3

      - uses: php-actions/phpunit@v3
        with:
          php_version: 8.3
          configuration: phpunit.xml
          test_suffix: 'Test'

      - uses: php-actions/phpstan@v3
        with:
          php_version: 8.3
          configuration: phpstan.neon
          memory_limit: 512m
